# reproducibility
seed: 42

# experiment name
experiment_name: default_name

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  max_epochs: 20
  fast_dev_run: False
  # precision: 16
  # amp_level: O2


# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_f1_micro
  mode: max
  patience: 50

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_f1_micro
  mode: max
  verbose: True
  save_top_k: 5
  dirpath: ${train.experiment_name}/