name: PyTorch CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: Setup the environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code formatter
        run: black --check .

      - name: Run unit tests
        run: |
          python -m unittest -v tests/unit/datamodule_test.py
          python -m unittest -v tests/unit/dataset_test.py
          python -m unittest -v tests/unit/raganato_reader_test.py
          python -m unittest -v tests/unit/model_test.py

      - name: Run train
        run: python -m src.train debug=True data.force_preprocessing=True max_samples=64 train.pl_trainer.max_epochs=2
